// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA056vxbFne8WkIVjYmxLRbynIkvJakIg0',
    appId: '1:40973681690:web:d9b5e40d673b913ae4fda3',
    messagingSenderId: '40973681690',
    projectId: 'vifacilita-ab14e',
    authDomain: 'vifacilita-ab14e.firebaseapp.com',
    storageBucket: 'vifacilita-ab14e.appspot.com',
    measurementId: 'G-J00XBJS4K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDETZf6GMebSruSxSMrNjLaRmgDM0ttI1I',
    appId: '1:40973681690:android:fd0c5f85239fdc4fe4fda3',
    messagingSenderId: '40973681690',
    projectId: 'vifacilita-ab14e',
    storageBucket: 'vifacilita-ab14e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvASCLZJb67nhC4kI8YbbWdRrF-kcnrkA',
    appId: '1:40973681690:ios:7e6713b395088428e4fda3',
    messagingSenderId: '40973681690',
    projectId: 'vifacilita-ab14e',
    storageBucket: 'vifacilita-ab14e.appspot.com',
    iosClientId: '40973681690-sccchnd362hh2susbp6or21g39q2edlp.apps.googleusercontent.com',
    iosBundleId: 'com.vifacilita.vifacilitaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvASCLZJb67nhC4kI8YbbWdRrF-kcnrkA',
    appId: '1:40973681690:ios:7e6713b395088428e4fda3',
    messagingSenderId: '40973681690',
    projectId: 'vifacilita-ab14e',
    storageBucket: 'vifacilita-ab14e.appspot.com',
    iosClientId: '40973681690-sccchnd362hh2susbp6or21g39q2edlp.apps.googleusercontent.com',
    iosBundleId: 'com.vifacilita.vifacilitaapp',
  );
}
